version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=postgres_password
  redis:
    image: 'redis:latest'
  nginx:
    restart: always
    depends_on:
      - api
      - client
    build:
      #dockerfile: Dockerfile #(when deploying in AWS Elastic Beanstalk)
      dockerfile: Dockerfile.dev #(saved copy to be used locally). For testing, use the first one, (elastic beanstalk implementation)
      context: ./nginx
    ports:
      - '3050:80'
  api:
    build:
      #dockerfile: Dockerfile #(when deploying in AWS Elastic Beanstalk)
      dockerfile: Dockerfile.dev #(saved copy to be used locally). For testing, use the first one, (elastic beanstalk implementation)
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  client:
    build:
      #dockerfile: Dockerfile #(when deploying in AWS Elastic Beanstalk)
      dockerfile: Dockerfile.dev #(saved copy to be used locally). For testing, use the first one, (elastic beanstalk implementation)
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    environment:
      - WDS_SOCKET_PORT=0
  worker:
    build:
      #dockerfile: Dockerfile #(when deploying in AWS Elastic Beanstalk)
      dockerfile: Dockerfile.dev #(saved copy to be used locally). For testing, use the first one, (elastic beanstalk implementation)
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
